image: docker:latest
services:
  - docker:dind
  - selenium/standalone-chrome:latest

stages:
  - build
  - test

before_script:
  - apt-get update 
  - export DISPLAY=:1
  - sleep 3  
  - chmod 775 /builds/glgomes21/automation-backoffice/src/test/resources/drivers/chromedriver

maven-build:
  image: maven:3.3.9-jdk-8
  stage: build
  script: "mvn test"
